"""initial_schema

Revision ID: ee1f644a0850
Revises: 
Create Date: 2026-05-09 15:27:34.161036

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1f644a0850'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_id'), ['target_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('checkpoint_path', sa.Text(), nullable=True),
    sa.Column('onnx_path', sa.Text(), nullable=True),
    sa.Column('precision_scores', sa.JSON(), nullable=True),
    sa.Column('recall_scores', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threshold_profiles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('violence_confidence_min', sa.Float(), nullable=False),
    sa.Column('fall_confidence_min', sa.Float(), nullable=False),
    sa.Column('crowd_confidence_min', sa.Float(), nullable=False),
    sa.Column('persistence_frames', sa.SmallInteger(), nullable=False),
    sa.Column('risk_low_max', sa.SmallInteger(), nullable=False),
    sa.Column('risk_medium_max', sa.SmallInteger(), nullable=False),
    sa.Column('ema_alpha', sa.Float(), nullable=False),
    sa.Column('cooldown_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('escalation_timeout_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('zone_configs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=False),
    sa.Column('suppress_event_types', sa.JSON(), nullable=True),
    sa.Column('peak_hours_schedule', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cameras',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('threshold_profile_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'OFFLINE', 'DISABLED', 'RECONNECTING', name='camera_status_enum'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fps_target', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['threshold_profile_id'], ['threshold_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_zone_id'), ['zone_id'], unique=False)

    op.create_table('incidents',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('VIOLENT_INTERACTION', 'FALL_COLLAPSE', 'CROWD_AGGRESSION', 'PERSON_DISTRESS', name='event_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'ACTIVE_REVIEW', 'EMERGENCY', 'RESOLVED', 'FALSE_POSITIVE', name='incident_status_enum'), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('confidence_at_alert', sa.Float(), nullable=False),
    sa.Column('people_count', sa.SmallInteger(), nullable=False),
    sa.Column('event_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_action', sa.Enum('CONFIRM', 'DISMISS', 'ESCALATE', 'FALSE_POSITIVE', name='review_action_enum'), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_event_start'), ['event_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alert_severity_enum'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('cooldown_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_from_id', sa.UUID(), nullable=True),
    sa.Column('escalation_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['escalated_from_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('evidence_clips',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sha256_hash', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('retention_tag', sa.Enum('TEMP_72H', 'STANDARD_30D', 'LONG_365D', 'PERMANENT', name='retention_tag_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_clips_incident_id'), ['incident_id'], unique=False)

    op.create_table('review_actions',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CONFIRM', 'DISMISS', 'ESCALATE', 'FALSE_POSITIVE', name='review_action_record_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence_override', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_actions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_actions_incident_id'), ['incident_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_actions_incident_id'))
        batch_op.drop_index(batch_op.f('ix_review_actions_action'))

    op.drop_table('review_actions')
    with op.batch_alter_table('evidence_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_clips_incident_id'))

    op.drop_table('evidence_clips')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_event_type'))
        batch_op.drop_index(batch_op.f('ix_incidents_event_start'))
        batch_op.drop_index(batch_op.f('ix_incidents_detected_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_camera_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_zone_id'))
        batch_op.drop_index(batch_op.f('ix_cameras_status'))

    op.drop_table('cameras')
    op.drop_table('zone_configs')
    op.drop_table('threshold_profiles')
    op.drop_table('model_versions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
